site_name: devex
site_url: https://anistajouri.github.io/devex/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

#plugins:
#  - social
#  - search

plugins:
  - material/search
  - git-revision-date
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
  - asciinema-player

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/anistajouri
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anis-tajouri-88a2976/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://github.com/anistajouri"  target="_blank" rel="noopener">Anis Tajouri</a>
