site_name: Developer Experience - Golden path to improve your productivity
site_url: https://anistajouri.github.io/devex/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal

nav:
  - About: 
    - Home: index.md
    - Devex components: devex/devex-components.md
    - Measuring Devex: devex/measuring-devex.md


  - Skills:
    - Skills: skills/how-to-succeed.md
    - Modern team: skills/modern-team.md
    - Learning path: skills/learning-path.md
    - Certifications: skills/certifications.md

  - Environment:   # Tools and local setup
    - nix: dev-env/nix.md
    - diagram: dev-env/diagram.md
    - Linux:
      - Basics: dev-env/linux.md
    - Git: dev-env/git.md
    - VS Code: dev-env/vscode.md
    - Neovim: dev-env/neovim.md
    - AI Tools:
      - GitHub Copilot: dev-env/copilot.md
      - GenAI for DevEx: dev-env/genai.md
    - Docker: dev-env/docker.md
    - Dagger: dev-env/dagger.md


  - Platforming CLI: # Building and deploying in the cloud
    - Platforms:
      - Google Cloud (GCP):
        - gcloud CLI: platforming/gcloud.md
      - Kubernetes:
        - kubectl CLI: platforming/kubectl.md
      - idp:
        - crossplane CLI: platforming/crossplane.md
    - Tools:
      - Terraform CLI: platforming/terraform.md

  - templates:
    - data:
      - Cloud engineering templates: templates-profiles/data-eng/data-eng.md
      - SQL/Modeling templates: templates-profiles/data-eng/data-modeling.md
      - RAG templates: templates-profiles/data-eng/data-rag.md
      - Analytics templates: templates-profiles/data-eng/data-analytics.md
    - Apps:
      - Microservices/Backend Templates: templates-profiles/apps-eng/backend.md
      - Frontend/Web: templates-profiles/apps-eng/web.md
      - Mobile: templates-profiles/apps-eng/mobile.md


    

plugins:
  - material/search
  - git-revision-date
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
  - asciinema-player

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/anistajouri
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anis-tajouri-88a2976/

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: True
  - meta
  - attr_list
  - mdx_truly_sane_lists
  - md_in_html
  - codehilite
  - callouts
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

copyright: |
  &copy; 2024 <a href="https://github.com/anistajouri"  target="_blank" rel="noopener">Anis Tajouri</a>
