site_name: Improve your productivity with developer experience
site_url: https://anistajouri.github.io/devex/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal

nav:
  - About: index.md

  - Core DevEx Principles:
    - What is DevEx?: devex-definition.md
    - Measuring DevEx: measuring-devex.md
    - Well-being: well-being.md

  - Skills & Certifications:
    - Modern Team: skills/modern-collaboration.md
    - Learning Paths: skills/learning-path-profiles.md
    - Onboarding New developer:skills/ onboarding.md
    - Certifications:
      - Cloud Certifications: skills/cloud-certification.md
      - GenAI Certifications: skills/genai-certification.md
      - Developer Achievements: skills/achievements.md


  - Dev Environment:   # Tools and local setup
    - VS Code: dev-env/vscode.md
    - AI Tools:
      - GitHub Copilot: dev-env/copilot.md
      - GenAI for DevEx: dev-env/genai.md
    - Linux Development:
      - Nix: dev-env/nix-shell.md
      - Linux Basics: dev-env/linux.md

  - Cloud-Native Development: # Building and deploying in the cloud
    - Platforms:
      - Google Cloud (GCP):
        - gcloud CLI: cloud/gcloud.md
      - Kubernetes:
        - Kubernetes (K8s): cloud/k8s.md
    - Tools:
      - Docker: cloud/docker.md
      - Terraform: cloud/terraform.md
    - CI/CD Pipelines: cloud/cicd-pipelines.md # Focus on automation

  - Developer Profiles:  # Configurations for specific roles
    - Cloud:
        - VS Code Setup: profiles/vscode-cloud-profile.md
        - Code Snippets: profiles/cloud-snippets.md
        - Templates: profiles/cloud-templates.md
    - Microservices/Backend:
        - Python:
          - VS Code Setup: profiles/vscode-python-profile.md
          - Code Snippets: profiles/python-snippets.md
          - Templates: profiles/python-templates.md
        - Java Spring Boot:
          - VS Code Setup: profiles/vscode-spring-boot-profile.md
          - Code Snippets: profiles/spring-boot-snippets.md
          - Templates: profiles/spring-boot-templates.md
        - Go:
          - VS Code Setup: profiles/vscode-golang-profile.md
          - Code Snippets: profiles/golang-snippets.md
          - Templates: profiles/golang-templates.md
    - Frontend/Web:
        - Angular:
          - VS Code Setup: profiles/vscode-angular-profile.md
          - Code Snippets: profiles/angular-snippets.md
          - Templates: profiles/angular-templates.md
    
    

plugins:
  - material/search
  - git-revision-date
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
  - asciinema-player

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/anistajouri
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anis-tajouri-88a2976/

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: True
  - meta
  - attr_list
  - mdx_truly_sane_lists
  - md_in_html
  - codehilite
  - callouts
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

copyright: |
  &copy; 2024 <a href="https://github.com/anistajouri"  target="_blank" rel="noopener">Anis Tajouri</a>
